name: Laravel CI/CD Deploy

on:
  push:
    branches:
      - main # Đảm bảo đúng branch của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: # Đảm bảo 'steps:' được thụt vào đúng cấp độ
      - name: Checkout Code # Dấu gạch ngang (-) và 'name'
        uses: actions/checkout@v4 # 'uses:' ở cấp độ này, thụt vào 2 dấu cách so với 'name'

      - name: Set up PHP Environment
        uses: shivammathur/setup-php@v2
        with: # 'with:' phải thụt vào 2 dấu cách so với 'uses:'
          php-version: '8.1' # Thuộc tính của 'with'
          extensions: mbstring, pdo_mysql, zip, gd
          tools: composer
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader # 'run:' ở cấp độ này, thụt vào 2 dấu cách so với 'name'

      # - name: Run Tests (Tùy chọn - Nên thêm vào) # Nếu bạn comment, hãy đảm bảo comment toàn bộ dòng
      #   run: php artisan test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | # Chú ý dấu gạch đứng (|) và nội dung script phải thụt vào
            cd /var/www/my-laravel-api
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan optimize
            sudo systemctl restart php8.1-fpm
